### Get all blogs
GET http://localhost:3001/api/blogs

### Create a new blog
POST http://localhost:3001/api/blogs
Content-Type: application/json

{
  "title": "My first bloge",
  "author": "John DoeE",
  "url": "http://example.com",
  "likes": 0
}